name: Go
on: [ push, pull_request ]
jobs:
  test:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.19.0-rc2'
      - name: Run tests and generate coverage report
        run: go test -coverprofile cover.out -covermode atomic ./... ./embeddings/store/diskstore/...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.7
        with:
          file: ./cover.out

  vet:
    name: go vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.19.0-rc2'
      - uses: actions/checkout@v2
      - name: go vet
        run: go vet ./... ./embeddings/store/diskstore/...

  gocyclo:
    name: gocyclo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.19.0-rc2'
      - name: Install gocyclo
        run: go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
      - uses: actions/checkout@v2
      - name: gocyclo
        run: gocyclo -over 15 -ignore "matfuncs/cpu" .

  staticcheck:
    name: staticcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.19.0-rc2'
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - uses: actions/checkout@v2
      - name: staticcheck
        run: staticcheck ./...
